### PR TITLE
ASIT-57: add code for checking reports/replies, blocking/unblocking n…

### PR DESCRIPTION
**Pull request by elruwen**
Adding code for:
- checking reports
- checking replies
- blocking numbers
- unblocking numbers

Adding more samples.

### CODE REVIEW

**Comment by Ox5f3759df** [comment]
Just general commentary:
I'm not sure why the end of php script closing ?> wasn't included in the original example.php but can you please add it to each functional example. 

Can you please update to README.md's usage section to stop referencing example.php and the new ones.

**Comment by Ox5f3759df** [comment]
Or do you plan to keep the original example? I assumed it was going to be removed.

**Comment by hellodaniel** [comment]
It's good practice to omit the closing tags on PHP documents (mostly to reduce the risk of output occurring).

**Comment by Ox5f3759df** [comment]
Ah yea, just read up on it. :-) thanks.

**Comment by elruwen** [comment]
I removed the original example file and reformatted the code.

**Comment by Ox5f3759df** [comment]
Looks good.

**Pull request merged**
